### ISSUE TITLE
Flat topic distributions in author-topic model

### ISSUE THREAD

**Issue by olavurmortensen** [arongdari/python-topic-model#8] opened 2016-10-04 10:21 UTC
I tried running the [author-topic model notebook](https://github.com/arongdari/python-topic-model/blob/master/notebook/AuthorTopicModel_example.ipynb). I noticed that the topic distributions of many authors were flat, meaning that all topics were equally likely. See example below.

<img src="http://i.imgur.com/iVLypL8.png" width=70% height=70%>

I did not change the notebook in any way, so I suspect there is some error in the algorithm/code, although I have no inkling of what it might be. Just thought I'd share.

Is someone else able to reproduce this, or is it just me? Or did I misunderstand, and this is actually expected to happen?

**Comment by dongwookim-ml** [comment] 2016-10-17 02:25
Hi,
I cannot reproduce the same result so far.
Did you find that all other others also exhibit the uniform distribution? If that's not the case, the sampler probably assigns zero token to the author.

**Comment by olavurmortensen** [comment] 2016-10-17 10:53
@arongdari No, not all the authors exhibit the uniform distribution, but it seems most of them do.

Just tried again on a different machine, starting from a clean virtual environment, same result.

Did you try to plot some other distributions? The ones that you plot in the notebook, 7 and 32, they're fine, it was when I tried plotting others I discovered something was wrong.

**Comment by dongwookim-ml** [comment] 2016-11-30 04:04
Sorry for the late reply. There are two possible reasons for this.
1. There is no document written by that author (due to some data cleaning steps)
2. No tokens are assigned to that author (with very low probability)

I just check the author with author_id = 1 who also has flat distribution, and it turns out that there is no document written by this author. So it corresponds to case 1 here. I suspect that the case 2 will not occur very frequently unless an author wrote only single document which is again written by many authors.

**Comment by olavurmortensen** [comment] 2016-11-30 12:21
You're probably right. I tried it myself on a different dataset (NIPS) and am not experiencing this problem.

**Closed as completed** 2016-12-01 03:01 UTC
